### ISSUE TITLE
Pro Spring Batch Chapter 2 Hello World Not Working

### ISSUE THREAD

**Issue by mohmdidris** [mminella/Pro-Spring-Batch-source-code#1]
Hi,
I'm a beginner to Spring Batch framework and i'm new to Spring Framework too. I'm trying to run a hello world program from the book Pro Spring Batch. i have imported the project into mt STS IDE from this site. I'm stuck with the issue given below 
"Failure to find com.springsource.bundlor:com.springsource.bundlor.maven:pom:1.0.0.RELEASE in http://repo.maven.apache.org/maven2 was cached 
 in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced". 
I'm using Spring Tool Suite  3.2.0.M1 and Maven 3.0.4 and JDK 1.7. Could somebody please help me solve this issue? It would be very much appreciated. 

Thanks,
Mohammed Idris

**Comment by mminella** [comment]
Unfortunately the current code (as checked in) requires maven 2.  I haven't had a chance to update it yet.  If you downgrade to maven 2 it will work.
